CREATE DATABASE universe;

CREATE TABLE galaxy (
galaxy_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
type INT NOT NULL,
distance_from_earth NUMERIC(10,2) NOT NULL,
description TEXT,
wearable BOOLEAN NOT NULL
);

CREATE TABLE star (
star_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
galaxy_id INT NOT NULL,
type INT NOT NULL,
temperature NUMERIC(10,2) NOT NULL,
FOREIGN KEY (galaxy_id) REFERENCES galaxy(galaxy_id)
);

CREATE TABLE planet (
planet_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
star_id INT NOT NULL,
type INT NOT NULL,
size NUMERIC(10,2) NOT NULL,
FOREIGN KEY (star_id) REFERENCES star(star_id)
);

CREATE TABLE moon (
moon_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
planet_id INT NOT NULL,
type INT NOT NULL,
distance_from_planet NUMERIC(10,2) NOT NULL,
FOREIGN KEY (planet_id) REFERENCES planet(planet_id)
);

CREATE TABLE comet (
comet_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL UNIQUE,
type INT NOT NULL,
size NUMERIC(10,2) NOT NULL,
last_seen DATE NOT NULL,
description TEXT,
visible BOOLEAN NOT NULL
);







